default_title: "CforGood"
meta_description: "La Communauté des Citoyens Responsables ! Le moyen le plus simple pour devenir un Acteur du Changement auq quotidien !"
meta_image: "logo.png" # Une image dans votre dossier app/assets/images/
twitter_account: "@CforGood" #indispensable pour les Twitter Cards