# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e51b0c4a49fc535e626e5ce706e58e9c06ff405c5677f6e9a3cdb9ea874a1378330f15441352ec2ca6ff99013aef07fa839813d84e92a7946e79a62efe139afc
  intercom_secure_mode_secret_key: <%= ENV["INTERCOM_KEY_SECURE"] %>


test:
  secret_key_base: 8265145deb3705a99ccb7d4389d40ad87ac6ea45a4b5db986747932040fe5dbe46ad33058ec2dfe772fc6e250630521b185723d41b0a1e191036848fb4cdb740

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  intercom_secure_mode_secret_key: <%= ENV["INTERCOM_KEY_SECURE"] %>
